theme: jekyll-theme-cayman
title: CARLA 2D Bounding Box Annotation Module
description: Automatic Vehicle 2D Bounding Box Annotation Module for object detection task in CARLA Simulator. Visit my github to get the code.
